# Generated by Django 2.2.20 on 2021-04-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrantInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('notsick', models.BooleanField(default=False, verbose_name='Not feeling any symptoms')),
            ],
        ),
    ]
